'use client';

import { useEffect, useRef, useState } from 'react';
import { EDUCATION, NAV, PROFILE, PROJECTS, RESEARCH, SKILLS } from '../lib/data';

const Arrow = () => <span aria-hidden="true">↗</span>;
function SectionHead({ index, label, title, accent }: { index: string; label: string; title: string; accent: string }) { return <div className="section-head"><span className="eyebrow">{index} — {label}</span><h2>{title} <em>{accent}</em></h2></div>; }

export default function Home() {
  const video = useRef<HTMLVideoElement>(null); const manual = useRef(false); const scrollDirection = useRef<'up' | 'down'>('down'); const [sound, setSound] = useState(false); const [menu, setMenu] = useState(false); const [active, setActive] = useState('about');
  useEffect(() => { const obs = new IntersectionObserver(es => es.forEach(e => e.isIntersecting && setActive(e.target.id)), { rootMargin: '-42% 0px -48% 0px' }); NAV.forEach(id => { const el = document.getElementById(id); if (el) obs.observe(el); }); return () => obs.disconnect(); }, []);
  useEffect(() => { const v = video.current; if (!v) return; let cancelled = false; const start = async () => { try { v.muted = false; await v.play(); window.localStorage.setItem('portfolio-intro-heard', 'true'); if (!cancelled) setSound(true); } catch { v.muted = true; await v.play().catch(() => {}); if (!cancelled) setSound(false); } }; start(); return () => { cancelled = true; }; }, []);
  useEffect(() => { const v = video.current; if (!v) return; let previousY = window.scrollY; const mute = () => { v.muted = true; setSound(false); }; const unmute = () => { v.muted = false; v.play().then(() => setSound(true)).catch(() => { v.muted = true; setSound(false); }); }; const onScroll = () => { const currentY = window.scrollY; if (currentY > previousY) { scrollDirection.current = 'down'; mute(); } else if (currentY < previousY) scrollDirection.current = 'up'; previousY = currentY; }; const observer = new IntersectionObserver(([entry]) => { if (scrollDirection.current === 'up' && entry.isIntersecting && entry.intersectionRatio >= 0.9) unmute(); if (!entry.isIntersecting || entry.intersectionRatio < 0.2) mute(); }, { threshold: [0, 0.2, 0.9, 1] }); observer.observe(v); window.addEventListener('scroll', onScroll, { passive: true }); return () => { observer.disconnect(); window.removeEventListener('scroll', onScroll); }; }, []);
  const playIntroduction = () => { const v = video.current; if (!v) return; manual.current = true; v.muted = false; v.play().then(() => { window.localStorage.setItem('portfolio-intro-heard', 'true'); setSound(true); }).catch(() => { v.muted = true; setSound(false); }); };
  useEffect(() => { if (window.localStorage.getItem('portfolio-intro-heard')) return; const startOnInteraction = () => playIntroduction(); window.addEventListener('pointerdown', startOnInteraction, { once: true }); return () => window.removeEventListener('pointerdown', startOnInteraction); }, []);
  const toggleSound = () => { const v = video.current; if (!v) return; manual.current = true; if (v.muted) { v.muted = false; setSound(true); v.play().catch(() => { v.muted = true; setSound(false); }); } else { v.muted = true; setSound(false); } };
  const handleEnded = () => { const v = video.current; if (!v) return; v.currentTime = 0; if (!manual.current) { v.muted = true; setSound(false); } v.play().catch(() => {}); };
  return <main>
    <header className="nav"><a href="#top" className="brand"><span>HH</span><b>{PROFILE.name}</b></a><nav>{NAV.map((id, i) => <a key={id} className={active === id ? 'active' : ''} href={'#' + id}>{String(i + 1).padStart(2, '0')} {id}</a>)}</nav><button className="menu-button" onClick={() => setMenu(true)}>Menu</button></header>
    {menu && <div className="mobile-menu"><button onClick={() => setMenu(false)} className="close">Close ×</button>{NAV.map((id, i) => <a key={id} href={'#' + id} onClick={() => setMenu(false)}><small>0{i + 1}</small>{id}</a>)}</div>}
    <section id="top" className="hero"><div className="hero-copy"><span className="eyebrow">Portfolio / 2026</span><h1>Building thoughtful<br /><em>interfaces.</em></h1><p>{PROFILE.summary.split('.')[0]}.</p><div className="actions"><a className="button dark" href="#work">Explore work <Arrow /></a><a className="button" href="#contact">Let&apos;s talk <Arrow /></a><a className="resume-link" href={PROFILE.resume} download>Résumé ↓</a></div></div><div className="hero-video"><span className="ghost">HASIBUL</span><video ref={video} autoPlay muted playsInline preload="auto" aria-label="Hasibul introducing himself" onEnded={handleEnded}><source src="/hero/intro.mp4" type="video/mp4" /></video><button className="sound" onClick={toggleSound} aria-label={sound ? 'Mute introduction' : 'Play introduction with sound'}>{sound ? 'Ⅱ' : '▶'}</button></div><div className="scroll-note">Scroll to explore <span>↓</span></div></section>
    <section id="about" className="section about"><SectionHead index="01" label="A little context" title="A developer who" accent="cares." /><div className="about-grid"><div><p className="lead">Hi, I&apos;m <em>Hasibul.</em></p><p>{PROFILE.summary}</p><div className="actions"><a className="button dark" href={PROFILE.resume} download>Download résumé <Arrow /></a><a className="button" href={PROFILE.github}>GitHub <Arrow /></a></div></div><div className="id-card"><div className="card-band">DEVELOPER ID</div><div className="portrait"><img src="/portrait.png" alt={PROFILE.name} /></div><strong>{PROFILE.name}</strong><span>{PROFILE.role}</span><dl><dt>DEPT.</dt><dd>Computer Science</dd><dt>VALID</dt><dd>2026</dd><dt>BASED</dt><dd>Dhaka, BD</dd></dl><div className="barcode" /></div><div className="facts"><span className="eyebrow">Quick facts</span><dl><dt>Location</dt><dd>{PROFILE.location}</dd><dt>Education</dt><dd>UIU · CSE</dd><dt>Email</dt><dd><a href={'mailto:' + PROFILE.email}>{PROFILE.email}</a></dd><dt>Focus</dt><dd>Accessible web interfaces</dd></dl><blockquote>“Turning UI designs into clean interfaces.”</blockquote></div></div></section>
    <section id="skills" className="section skills"><SectionHead index="02" label="The toolkit" title="A stack with" accent="range." /><div className="skill-grid">{SKILLS.map(s => <div className="skill" key={s.name}><small>{s.number}</small><b>{s.symbol}</b><span>{s.name}</span><em>{s.family}</em></div>)}</div></section>
    <section id="work" className="section work"><SectionHead index="03" label="Selected work" title="Things I&apos;ve" accent="built." /><div className="project-list">{PROJECTS.map((p, i) => <article className="project" key={p.title}><div className="project-number">0{i + 1}</div><div className="project-main"><span className="eyebrow">{p.kicker}</span><h3>{p.title}</h3><p>{p.description}</p><ul>{p.details.map(d => <li key={d}>{d}</li>)}</ul><div className="project-meta"><span>{p.date}</span><span>{p.tech}</span>{p.github && <a href={p.github}>View on GitHub <Arrow /></a>}</div></div>{p.video ? <a className="video-card" href={p.video} target="_blank" rel="noopener noreferrer" aria-label={`Watch the ${p.title} demo on YouTube`}><img src={`https://img.youtube.com/vi/${(p.video.match(/[?&]v=([A-Za-z0-9_-]+)/) ?? [])[1]}/hqdefault.jpg`} alt={`${p.title} demo video`} loading="lazy" /><span className="play" aria-hidden="true">▶</span><strong>Watch demo</strong></a> : p.image ? <div className="image-card"><img src={p.image} alt={`${p.title} screenshot`} loading="lazy" /></div> : <div className="ui-card" aria-label="Illustrative UI"><div className="ui-top"><i /><i /><i /></div><div className="ui-line wide" /><div className="ui-line" /><div className="ui-blocks"><i /><i /><i /></div><strong>Illustrative UI</strong></div>}</article>)}</div></section>
    <section id="experience" className="section experience"><SectionHead index="04" label="The path so far" title="Learning by" accent="doing." /><div className="timeline">{EDUCATION.map(item => <article key={item.title}><time>{item.year}</time><div><h3>{item.title}</h3><p>{item.place} · {item.detail}</p></div></article>)}<article><time>Next</time><div><h3>Your team?</h3><p>Looking for a front-end internship.</p></div></article></div></section>
    <section id="achievements" className="section research"><SectionHead index="05" label="Beyond the interface" title="Curiosity is" accent="ongoing." /><div className="research-grid">{RESEARCH.map((r, i) => <article key={r.title}><span>0{i + 1}</span><h3>{r.title}</h3><p>{r.place}</p></article>)}</div><div className="activity"><span className="eyebrow">Activities</span><p>General Member, Computer Club, UIU. Built rover and RoboSoccer robots using Arduino, sensors, ESP-CAM, and embedded systems.</p></div></section>
    <section id="contact" className="contact"><span className="eyebrow">06 — Contact</span><h2>Let&apos;s build<br /><em>something together.</em></h2><a className="email" href={'mailto:' + PROFILE.email}>{PROFILE.email} <Arrow /></a><div className="contact-links"><a href={'tel:' + PROFILE.phone}>{PROFILE.phone}</a><a href={PROFILE.github}>GitHub <Arrow /></a><a href={PROFILE.linkedin}>LinkedIn <Arrow /></a></div><footer><span>© 2026 {PROFILE.name}</span><a href="#top">Back to top ↑</a><span>Built with Next.js</span></footer></section>
  </main>;
}
